### ISSUE TITLE
Add support for Influxdb2

### ISSUE THREAD

**Issue by breadlysm** [breadlysm/speedtest-to-influxdb#10]
It looks like the write commands and authentication remain largely intact or have compatible methods. 

The line protocol data though will need a change to include extra buckets. 
https://docs.influxdata.com/influxdb/v2.0/api/#tag/Write

**Comment by twsl** [comment]
See https://github.com/influxdata/influxdb-client-python

**Comment by breadlysm** [comment]
Split this into separate issues.

**Comment by breadlysm** [comment]
#12 #
#13 
#14 
#15
