### ISSUE TITLE
jitter ?

### ISSUE THREAD

**Issue by P6g9YHK6** [breadlysm/speedtest-to-influxdb#31]
would it be possible to add to the dashboard a ping jitter panel?
here is an exemple of a speed test with a jitter display http://ting.speedtestcustom.com/

**Comment by ChiefGyk3D** [comment]
So Jitter is included partially already in alternative dashboard and it looks like pulled in with the data so it wouldn't be too hard I suppose for someone who has the knowledge to add it. 
https://github.com/breadlysm/SpeedFlux/blob/master/GrafanaDash-SpeedTests.json

![image](https://user-images.githubusercontent.com/19499446/186324382-72cfc7f6-3310-44a7-9fd6-17ef5ef3e462.png)
![image](https://user-images.githubusercontent.com/19499446/186324419-9dea9a9b-f012-4ad7-b90d-773f23e8963a.png)
![image](https://user-images.githubusercontent.com/19499446/186324455-3816ba1e-18b1-47ee-ace9-956397d390d2.png)

**Comment by Selta** [comment]
It's fairly simple to include jitter and latency in different panels of a dashboard.
One example query that will get the values for you and alias (rename) them as `Latency ms` and `Jitter ms` is:
```
SELECT "latency" AS "Latency ms", "jitter" AS "Jitter ms" FROM "ping" WHERE ("namespace" =~ /^$namespace$/) AND $timeFilter GROUP BY "server_name"
```

One easy way to simply dig around the available data is to go into Explore:
![image](https://user-images.githubusercontent.com/4176070/193441285-661b2e69-bb16-4f8f-83b2-91d3df33c64a.png)

Once in there, you can use the UI to build queries. This setup will produce a table that shows the datetime, server_name, jitter, and latency values:
![image](https://user-images.githubusercontent.com/4176070/193441381-c1a4c40d-3e26-4dd1-80f0-b5c406b3ada9.png)

Once you have a handle on the querying, it's as simple as making a new panel, or inserting the queries into an existing panel to add the columns to a table.

**Comment by P6g9YHK6** [comment]
Thanks everyone i didn't know that the jitter was a value already logged by the tool i have made my little panel to have an overview of the jittter per ISP

![image](https://user-images.githubusercontent.com/17877371/221436619-63180d24-08d4-40f4-82aa-c9d761f454fd.png)
