### ISSUE TITLE
How to show speeds from different speedtest servers

### ISSUE THREAD

**Issue by nmcc1212** [breadlysm/speedtest-to-influxdb#32]
I have the `SPEEDTEST_SERVER_ID` environment variable empty, so I assume it will just choose the best server but Grafana looks like this 
<img width="1446" alt="Screenshot 2022-09-30 at 12 11 27 pm" src="https://user-images.githubusercontent.com/48334675/193257750-f8c95777-5bd1-4b4e-ab0b-74217f949fad.png">

with the server and location fields empty

**Comment by Selta** [comment]
What are you setting for `INFLUX_DB_TAGS`? I believe you need `server_name`, `server_location`, `server_host`, and `speedtest_url` at a minimum, for the included dashboard.

**Comment by nmcc1212** [comment]
just set it to * as a wildcard and works perfectly. Thanks!
